module.exports = {
    currencies: {
        'AED':{'main':'United Arab Emirates dirham', 'fraction':'Fils'},
        'AFN':{'main':'Afghan afghani', 'fraction':'Pul'},
        'ANG':{'main':'Netherlands Antillean guilder', 'fraction':'Cent'},
        'ARS':{'main':'Argentine peso', 'fraction':'Centavo'},
        'AUD':{'main':'Australian dollar', 'fraction':'Cent'},
        'BRL':{'main':'real', 'fraction':'Centavo'},
        'CAD':{'main':'Canadian dollar', 'fraction':'Cent'},
        'CHF':{'main':'Swiss franc', 'fraction':'Rappen'},
        'CNY':{'main':'yuan', 'fraction':'Fen'},
        'DKK':{'main':'Danish krone', 'fraction':'Øre'},
        'DZD':{'main':'Algerian dinar', 'fraction':'Santeem'},
        'EGP':{'main':'Egyptian pound', 'fraction':'Piastre'},
        'EUR':{'main':'Euro', 'fraction':'Cent'},
        'GBP':{'main':'Pound', 'fraction':'Penny'},
        'GHC':{'main':'Ghana Cedi', 'fraction':'Pesewa'},
        'GHS':{'main':'Ghana Cedi', 'fraction':'Pesewa'},
        'HKD':{'main':'Hong Kong dollar', 'fraction':'Cent'},
        'ILS':{'main':'Israeli new shekel', 'fraction':'Agora'},
        'INR':{'main':'Indian rupee', 'fraction':'Paisa'},
        'IQD':{'main':'Iraqi dinar', 'fraction':'Fils'},
        'IRR':{'main':'Iranian rial', 'fraction':'Dinar'},
        'JMD':{'main':'Jamaican dollar', 'fraction':'Cent'},
        'JOD':{'main':'Jordanian dinar', 'fraction':'Piastre'},
        'JPY':{'main':'Japanese yen', 'fraction':'Sen'},
        'KES':{'main':'Kenyan shilling', 'fraction':'Cent'},
        'KPW':{'main':'North Korean won', 'fraction':'Chon'},
        'KRW':{'main':'South Korean won', 'fraction':'Jeon'},
        'KWD':{'main':'Kuwaiti dinar', 'fraction':'Fils'},
        'LYD':{'main':'Libyan dinar', 'fraction':'Dirham'},
        'MXN':{'main':'Mexican peso', 'fraction':'Centavo'},
        'MAD':{'main':'Moroccan dirham', 'fraction':'Centime'},
        'MUR':{'main':'Rupee', 'fraction':'Cent'},
        'NGN':{'main':'Naira', 'fraction':'Kobo'},
        'NZD':{'main':'New Zealand dollar', 'fraction':'Cent'},
        'PEN':{'main':'Peruvian sol', 'fraction':'Céntimo'},
        'PHP':{'main':'Philippine peso', 'fraction':'Sentimo'},
        'PYG':{'main':'Paraguayan guaraní', 'fraction':'Céntimo'},
        'QAR':{'main':'Qatari riyal', 'fraction':'Dirham'},
        'RON':{'main':'Romanian leu', 'fraction':'Ban'},
        'RSD':{'main':'Serbian dinar', 'fraction':'Para'},
        'RUB':{'main':'Russian ruble', 'fraction':'Kopek'},
        'RWF':{'main':'Rwandan franc', 'fraction':'Centime'},
        'SAR':{'main':'Saudi riyal', 'fraction':'Halala'},
        'SDG':{'main':'Sudanese pound', 'fraction':'Piastre'},
        'SEK':{'main':'Swedish krona', 'fraction':'Öre'},
        'SGD':{'main':'Singapore dollar', 'fraction':'Cent'},
        'SHP':{'main':'Saint Helena pound', 'fraction':'Penny'},
        'SYP':{'main':'Syrian pound', 'fraction':'Piastre'},
        'THB':{'main':'Thai baht', 'fraction':'Satang'},
        'TND':{'main':'Tunisian dinar', 'fraction':'Millime'},
        'TRY':{'main':'Turkish lira', 'fraction':'Kuruş'},
        'TWD':{'main':'New Taiwan dollar', 'fraction':'Cent'},
        'UGX':{'main':'Ugandan shilling', 'fraction':'Cent'},
        'USD':{'main':'US Dollar', 'fraction':'Cent'},
        'VES':{'main':'Venezuelan bolívar soberano', 'fraction':'Céntimo'},
        'XAF':{'main':'Central African CFA franc', 'fraction':'Centime'},
        'XCD':{'main':'Eastern Caribbean dollar', 'fraction':'Cent'},
        'XOF':{'main':'West African CFA franc', 'fraction':'Centime'},
        'XPF':{'main':'CFP franc', 'fraction':'Centime'},
        'YER':{'main':'Yemeni rial', 'fraction':'Fils'},
        'ZAR':{'main':'South African rand', 'fraction':'Cent'}
    },

    getInfo(currencyCode){
        return currencyCode ? this.currencies[currencyCode.toUpperCase()] : {'main':'', 'fraction':''};
    }
};